  on:
    pull_request:
      branches:
        - integration
      types:
        - closed

  jobs:
    pr-replication:
      if: ${{ github.event.pull_request.merged == true }}
      name: PR Replication
      runs-on: ubuntu-latest
      steps:
        - name: Push code from integration to integration-ecs branch
          run: |
            git init
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git checkout origin/integration-ecs
            git merge origin/integration
            git commit -m "Replicating PR from integration to integration-ecs"
            git push origin integration-ecs
